# Generated by Django 5.0.3 on 2024-10-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("some_name", models.CharField(max_length=32)),
                ("some_number", models.IntegerField()),
            ],
        ),
    ]
